@MailSyncer.API_HostAddress = http://localhost:5200


POST {{MailSyncer.API_HostAddress}}/api/contacts/sync
Accept: application/json

###

GET {{MailSyncer.API_HostAddress}}/api/contacts
Accept: application/json

###

DELETE {{MailSyncer.API_HostAddress}}/api/contacts
Accept: application/json

###